name: Deploy

on:
  push:
    branches:
      - main
jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Compile jar file
        run: cd code/demo && ./gradlew bootJar

  build-test-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install dependencies
        run: cd infra && npm install
      - name: Building
        run: cd infra && npm run build
      - name: Run Tests
        run: cd infra && npm run test
      - name: Synthesize cloudformation
        run: cd infra && npm run cdk synth

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: deploy as DEV
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: cd infra && npm run cdk deploy
